### ISSUE TITLE
Add pyc etc to gitignore file

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wynSite#1]
As per title.  The are random pyc files being committed to the repo.

**Comment by WnndGws** [comment]
Example?

**Comment by ammgws** [comment]
[This](https://github.com/WnndGws/wynSite/tree/master/wynSite/__pycache__) whole directory, and also [this](https://github.com/WnndGws/wynSite/tree/master/bin/__pycache__) one.

Though for the second one, the parent folder shouldn't really be there in the first place Seems like you accidentally added the whole venv to git as well?
